# Generated by Django 4.0.3 on 2022-05-13 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='auction',
            unique_together={('user', 'post')},
        ),
    ]
