# Generated by Django 4.0.3 on 2022-05-17 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0007_remove_sharing_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharing',
            name='description',
        ),
    ]
