# Generated by Django 4.0.3 on 2022-04-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0003_friendrequest_user_friends_delete_friend_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to='avatar/%Y/%m'),
        ),
    ]
