# Generated by Django 4.0.3 on 2022-04-29 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/%Y/%m'),
        ),
    ]
