# Generated by Django 4.0.3 on 2022-04-30 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0005_alter_post_title_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='products',
        ),
        migrations.AddField(
            model_name='post',
            name='products',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='demoApp.product'),
        ),
        migrations.DeleteModel(
            name='ProductPostDetail',
        ),
    ]
