# Generated by Django 4.0.3 on 2022-05-04 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0006_remove_post_products_post_products_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='products',
            new_name='product',
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('type', models.PositiveIntegerField(choices=[(0, 'Like'), (1, 'Unlike')], default=1)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demoApp.post')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
