# Generated by Django 4.0.3 on 2022-05-05 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0008_alter_user_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='creators',
        ),
    ]
