# Generated by Django 4.0.3 on 2022-05-05 18:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0009_remove_post_creators'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='creators',
            field=models.ManyToManyField(related_name='users_comment_post', through='demoApp.Comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
