# Generated by Django 4.0.3 on 2022-05-06 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0010_post_creators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='auctioneers',
        ),
        migrations.RemoveField(
            model_name='post',
            name='creators',
        ),
        migrations.RemoveField(
            model_name='post',
            name='shared',
        ),
    ]
