# Generated by Django 4.0.3 on 2022-05-06 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demoApp', '0012_post_auctioneers_post_creators_post_shared'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='creators',
            new_name='creators_comment',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='shared',
            new_name='people_shared',
        ),
    ]
